# Generated by Django 3.1.4 on 2020-12-28 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='token',
            new_name='token_type',
        ),
    ]
